services:
  synapse:
    image: matrixdotorg/synapse:v1.105.0
    hostname: matrix.local.crz.li
    volumes:
      - data:/data
      - ./synapse/config:/config
    ports:
      - 8008:8008
    environment:
      - SYNAPSE_SERVER_NAME=matrix.local.crz.li
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_DIR=/config
  element:
    image: vectorim/element-web:v1.11.64
    ports:
      - 8000:80
    volumes:
      - ./elements/config.json:/app/config.json

volumes:
  data: {}
