# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "matrix.local.crz.li"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
log_config: /config/matrix.local.crz.li.log.config
media_store_path: /data/media_store
enable_registration: true
enable_registration_without_verification: true
registration_shared_secret: "Ri.4V;LoFmAzun:vVVA@A54^R_KJxZb#N_EBrLSBh6vXP^vslZ"
report_stats: false
macaroon_secret_key: ";_duJr03AWqZ00yMxVxfA25es&fD7g^6@g^8w8wKK*q2e9yryQ"
form_secret: "XK.5uyehFO4tGG@46r_^btEYs1MeCY=h+SbBde42*Zex=-YJjs"
signing_key_path: /config/matrix.local.crz.li.signing.key
trusted_key_servers:
  - server_name: "matrix.org"
